#!/bin/bash

# The script can compile files of different languages in an easy way.

test "$1" != "" || exit 1

# C.
comp_c()
{
	x=${1%%.c*}		# '%%' %%O* --> 截取最后"O"的左侧str，删除右侧str
	echo ${x}		# '%' --> 截取最前"O"的左侧str。
	gcc -g -o ${x} $1
}

# C++.
comp_c_plus()
{	
	x=${1%%.cpp*}
	echo ${x}
	g++ $1 -o ${x}
}

case ${1##*.} in		# '##' ##*O --> 截取最后"."的右侧str，保留左侧str
	"c") comp_c $1 ;;
	"cpp") comp_c_plus $1 ;;
esac

exit 1
