#!/bin/bash

# The script can compile files of different languages in an easy way.

cmd="${0##*/}"	# In case of modifying the name of file.

# Usage
usage()
{
	cat <<-EOF >&2
	Usage: $cmd <file>
	[Only support '.c' '.cpp' files]
	EOF
}

# C.
comp_c()
{
	x=${1%%.c*}		# '%%' %%O* --> 截取最后"O"的左侧str，删除右侧str
					# '%' --> 截取最前"O"的左侧str。
	gcc -g -o ${x} $1 && echo ${x}
}

# C++.
comp_c_plus()
{
	x=${1%%.cpp*}
	g++ $1 -o ${x} && echo ${x}
}

test -z $1 && usage && exit 1


case ${1##*.} in		# '##' ##*O --> 截取最后"."的右侧str，删除左侧str
	"c") comp_c $1 ;;
	"cpp") comp_c_plus $1 ;;
	*) echo "Cannot Compile the file!" ;;
esac

exit 1
