#!/bin/bash

#This shell will count the probability of dice side with RANDOM.

Throw_Times=907

Freq=(0 0 0 3 0 0)		# define the frequency array of 1~6.

print_result()
{
	for var in {1..6}	# {a..b} both a & b should be constant.
	do
	tmp=${Freq[$((var-1))]}
	# A great example of xx% showing in shell !!!
	prob=`awk 'BEGIN{printf "%.1f%%", ('$tmp'/'$Throw_Times')*100}'`
	echo "${var}: $tmp ----> $prob"
	done
}

update_count()
{
	lct=$(($1 - 1))
	((Freq[$lct]+=1))		# important format in calculation!!!
}

throw_dice()
{
	while [ "$((throw++))" -lt "$Throw_Times" ]		# another loop method.
	do
	#When u launch this shell, $RANDOM will work.
	#When u denbug this shell, it will ignore the value of $RANDOM
	rst=$(($RANDOM%6 + 1))
	update_count $rst
	done
}

throw_dice && print_result

exit 0

