#!/bin/bash

if [ "x$1" == "x" ]; then
	read -p "Please give the key words:" sf
else
	sf=$1
fi
if [ "x$2" == "x" ]; then
	# grep $1 in the dir and subdir
	if [ "${sf}" != "" ]; then
		# 2>/dev/null can prevent printing error messages!
  		grep -rns --color "${sf}" * 2>/dev/null
	else 
  	echo "Search failed!"
	fi
else
	# find the file "$1" which should contain "$2"
	sm=$2
	find ./ -type f -name "${sf}" | xargs grep -n --color "${sm}" 2>/dev/null
fi

