#!/bin/bash

cmd="${0##*/}"

usage()
{
	cat <<-EOF >&2
	Usage: $cmd <keyword> [<file>]
	-With <file>, the cmd means:
	   find <file> which contains <keyword> in dir.
	-With no <file>, the cmd means:
	   grep <keyword> in dir.
	-Keyword and file can be regular expression.
	EOF
}

test -z $1 && usage && exit 1
key=$1

if [ "x$2" == "x" ]; then
	# 2>/dev/null can prevent printing error messages!
  	grep -rns --color "$key" * 2>/dev/null
else
	# find the file "$1" which should contain "$2"
	fname=$2
	find ./ -type f -name "$fname" | xargs grep -n --color "$key" 2>/dev/null
fi

