#!/bin/bash

# From LeetCode: Print the frequency of each word in file.(Descending Order)

file="Test.txt"

Tch_file()
{
	cat <<-EOF > $file
	I like good food .
	food is good for us .
	How is the food ?
	I like us , good .
	EOF
}

Freq()
{
	cat $file | xargs -n 1 | sort | uniq -c | sort -nr | awk '{print $2" "$1}'
	# 'xargs' pip; 'uniq -c' print frequency; 'sort -nr' descending order by num
}

Tch_file && Freq && rm -f $file

